#+TITLE: Chronos

* spec
вебсервер хранит информацию о профилях пользователей и экспортирует данные через REST API
http server stored user profiles and exports data with REST API

echo https://echo.labstack.com/
Postman

persistence with MongoDB
 - read
 - update
 - create
 - delete
REST API
 - GET request retrieves data from a resource. For example, you’d use a GET request to retrieve a record from a database.
 - DELETE request deletes a resource.
 - PUT request updates an existing resource.
 - POST request creates a new resource, such as a new record in a database.

Field of the entity User
- ID (object id (mongo db))
- first name (string)
- last name (string)
- age (int)
- city (string)
- country (string)
#+begin_src go
type User struct {
	first   string `json:”first”   bson:"first"   validate:"required"`
	last    string `json:”last”    bson:"last"    validate:"required"`
	age     int    `json:”age”     bson:"age"     validate:"required"`
	city    string `json:”city”    bson:"city"    validate: "required"`
	country string `json:”country” bson:"country" validate: "required"`
}
#+end_src

Inteface
- add user Insert
- delete user by id - deleteByID
- get by id
- get by first/last name
- get by city
- get by country
- get all users
#+begin_src go
type Store interface {
	storage.StoreBase
	Get(id id.ID) (User, error)
	GetByName(name string) (User, error)
	GetByName(name string) (User, error)
	GetByCity(city string) (User, error)
	GetByCountry(string string) (User, error)
	Update(id id.ID, update User) (User, error)
	Insert(o User) error
	Delete(id id.ID) error
	Exists(name string) (bool, error)
}
#+end_src

* readers
 - https://www.avcosystems.com/blog/mongo-go/
 - https://golangdocs.com/mongodb-golang
 - https://www.mongodb.com/blog/post/quick-start-golang--mongodb--how-to-read-documents
 - https://www.mongodb.com/blog/post/quick-start-golang--mongodb--data-aggregation-pipeline
* rest
#+begin_src restclient
GET http://localhost:4000/api/v1/users
#+end_src

#+RESULTS:
#+BEGIN_SRC js
{
  "success": true,
  "data": [
    {
      "id": "6004176776694f24fb635af0",
      "First": "Sam"
    }
  ]
}

// GET http://localhost:4000/api/v1/users
// HTTP/1.1 200 OK
// Content-Type: application/json; charset=UTF-8
// Date: Sun, 17 Jan 2021 10:54:52 GMT
// Content-Length: 112
// Request duration: 0.009527s
#+END_SRC

#+begin_src restclient
GET http://localhost:4000/api/v1/users/6004176776694f24fb635af0
#+end_src

#+begin_src restclient
DELETE http://localhost:4000/api/v1/users/6004176776694f24fb635af0
#+end_src

#+begin_src restclient
POST http://localhost:4000/api/v1/users
Content-Type: application/json

{
      "first":  "iysh",
}
#+end_src

#+begin_src restclient
PUT http://localhost:4000/api/v1/users/6003edc4905c04207f497152
Content-Type: application/json

{
      "name":  "iysh",
      "email": "iyshrylana",
      "age":   45
}
#+end_src

* tasks
 - [X] install setup
   + [X] echo
   + [X] MongoDb
   + [X] Postman
   + [X] golang
 - [X] setup emacs
   + [X] rest
   + [X] golang
 - [X] commit "docs: plan tasks"
 - [X] intermission
 - [X] describe a single user entity with a name
 - [X] route getUsers to /
 - [X] commit "feat: GET all users"
 - [X] persist a user object and GET it by id
 - [X] commit "feat: GET a user by id"
 - [X] intermission
 - [X] delete a user with DELETE
 - [X] commit "feat: DELETE a user by id"
 - [ ] create a user with POST
 - [ ] commit "feat: POST a new user"
 - [ ] mutate a user object with PUT
 - [ ] commit "feat: PUT a user name by id"
 - [ ] intermission
 - [ ] refactor
 - [ ] commit "refactor: <...>"
